bibimbap: rice beef
	echo "Here is your bibimbap."

rice:
	echo "Here's some rice."

beef: fryingPan sauce
	echo "Here's some beef"

fryingPan:
	echo "We have a frying pan at this location:"
	pwd

sauce: 
	cat sauce.txt